# Generated by Django 4.0.5 on 2022-06-22 01:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant_Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photoEtudiant', models.ImageField(null=True, upload_to='')),
                ('nni', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('carteIdentite', models.ImageField(null=True, upload_to='')),
                ('numBac', models.IntegerField()),
                ('serie', models.CharField(max_length=200)),
                ('releveNote', models.ImageField(null=True, upload_to='')),
                ('session', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('pays', models.CharField(max_length=200)),
                ('AnObtantionBac', models.DateField()),
                ('niveau', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photoEtudiant', models.ImageField(null=True, upload_to='')),
                ('nni', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('carteIdentite', models.ImageField(null=True, upload_to='')),
                ('numBac', models.IntegerField()),
                ('serie', models.CharField(max_length=200)),
                ('releveNote', models.ImageField(null=True, upload_to='')),
                ('session', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('pays', models.CharField(max_length=200)),
                ('AnObtantionBac', models.DateField()),
                ('niveau', models.CharField(max_length=200, null=True)),
                ('licence', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nni', models.IntegerField()),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('filiere', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Licence',
            fields=[
                ('etudiant_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Master',
            fields=[
                ('etudiant_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_master',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Licence',
            fields=[
                ('etudiant_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Master',
            fields=[
                ('etudiant_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_master',),
        ),
        migrations.CreateModel(
            name='Filiere_Licence',
            fields=[
                ('filiere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.filiere')),
            ],
            bases=('Inscrire.filiere',),
        ),
        migrations.CreateModel(
            name='Filiere_Master',
            fields=[
                ('filiere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.filiere')),
            ],
            bases=('Inscrire.filiere',),
        ),
        migrations.CreateModel(
            name='Etudiant_Licence_Public_L1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroInscription', models.CharField(max_length=6)),
                ('nom', models.CharField(max_length=200)),
                ('photoEtudiant', models.ImageField(null=True, upload_to='')),
                ('nni', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.CharField(max_length=200)),
                ('carteIdentite', models.ImageField(null=True, upload_to='')),
                ('numBac', models.IntegerField()),
                ('serie', models.CharField(max_length=200)),
                ('releveNote', models.ImageField(null=True, upload_to='')),
                ('session', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('pays', models.CharField(max_length=200)),
                ('AnObtantionBac', models.DateField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscrire.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('filiere', models.ManyToManyField(blank=True, related_name='filiere', to='Inscrire.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Licence_Niveau1',
            fields=[
                ('etudiant_prive_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_prive_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_prive_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Licence_Niveau2',
            fields=[
                ('etudiant_prive_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_prive_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_prive_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Licence_Niveau3',
            fields=[
                ('etudiant_prive_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_prive_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_prive_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Master_Niveau1',
            fields=[
                ('etudiant_prive_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_prive_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_prive_master',),
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Master_Niveau2',
            fields=[
                ('etudiant_prive_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_prive_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_prive_master',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Licence_Niveau1',
            fields=[
                ('etudiant_public_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_public_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_public_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Licence_Niveau2',
            fields=[
                ('etudiant_public_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_public_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_public_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Licence_Niveau3',
            fields=[
                ('etudiant_public_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_public_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_public_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Master_Niveau1',
            fields=[
                ('etudiant_public_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_public_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_public_master',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Master_Niveau2',
            fields=[
                ('etudiant_public_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_public_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_public_master',),
        ),
        migrations.AddField(
            model_name='etudiant_master',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscrire.filiere_master'),
        ),
        migrations.AddField(
            model_name='etudiant_licence',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscrire.filiere_licence'),
        ),
    ]
